name: Package src folder

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GFPGAN-ncnn-vulkan-src
          path: src
          retention-days: 7
